version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kent250/marketplace-api:latest
    container_name: marketplace-API-container
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    depends_on:
      - db
    env_file: 
      - .env
    environment:
      - HOST=db
    networks:
      - marketplace-network

  db:
    image: postgres:16.3
    container_name: marketplace-db-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 50

networks:
  marketplace-network:
    name: marketplace-network

volumes:
  postgres_data:
    name: marketplace-postgres-data